---
server:
  port: 0
spring:
  config:
    activate:
      on-profile: default
  cloud:
    kubernetes:
      config:
        enabled: false

  application:
    name: product-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
      loadbalancer:
        mode: service

eureka:
  client:
    enabled: false