server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: default
  application:
    name: api-gateway
  cloud:
    kubernetes:
      config:
        enabled: false
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/**
            - Method=GET
          filters:
        #    - name: AuthorizationHeaderFilter
        #      args:
        #        whiteList:
        #          jeminToken: jemin
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true # 전체 namespace를 다 검색
      loadbalancer:
        mode: service # service를 사용해서 검색
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/users/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

eureka:
  client:
    enabled: false
