server:
  port: 0

---

spring:
  config:
    activate:
      on-profile: default
  cloud:
    kubernetes:
      config:
        enabled: false

  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

eureka:
  client:
    enabled: false